export const questions = [
	{
		id: "Q1",
		text: "Quelle est la raison de votre présence en gare ?",
		options: [
			{ text: "Je vais prendre le train", next: "Q2" },
			{ text: "Je viens de descendre du train", next: "end" },
			{ text: "J'accompagne des voyageurs qui partent / J'attends des voyageurs qui arrivent", next: "Q2_nv" },
			{ text: "Autre raison (achat billet, commerces en gare...)", next: "Q2_nv" },
		],
	},
	{
		id: "Q2",
		text: "Quelle est l'origine de votre déplacement ? (D'où êtes-vous parti pour arriver à la gare ?)",
		options: [
			{ text: "Vierzon", next: "Q2a" },
			{ text: "Autre commune", next: "Q2_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q2_precision",
		text: "Préciser le nom de la commune :",
		freeText: true,
		next: "Q3",
	},
	{
		id: "Q2a",
		text: "De quelle rue de Vierzon venez-vous ?",
		streetInput: true,
		freeTextPlaceholder: "Nom de la rue",
		next: "Q3",
	},
	{
		id: "Q3",
		text: "Quel mode de transport avez-vous utilisé pour vous rendre à la gare ?",
		options: [
			{ text: "A pied", next: "Q4" },
			{ text: "En voiture -- en tant que conducteur", next: "Q3a" },
			{ text: "En voiture -- en tant que passager", next: "Q3b" },
			{ text: "En covoiturage avec un autre usager du train", next: "Q4" },
			{ text: "En bus/car", next: "Q3c" },
			{ text: "A vélo", next: "Q3d" },
			{ text: "En trottinette", next: "Q3d" },
			{ text: "En Taxi/VTC", next: "Q4" },
			{ text: "En 2 roues Motorisé (Moto, scooter...)", next: "Q3a" },
			{ text: "En train - je fais une correspondance", next: "Q4" },
			{ text: "Autre", next: "Q3_autre", requiresPrecision: true },
		],
	},
	{
		id: "Q3_autre",
		text: "Précisez le mode de transport utilisé :",
		freeText: true,
		next: "Q4",
	},
	{
		id: "Q3a",
		text: "Où avez-vous stationné votre véhicule ?",
		options: [
			{ text: "Sur le parking Effia longue durée", next: "Q3a_duree" },
			{ text: "Sur le parking courte durée sur le parvis", next: "Q3a_duree" },
			{ text: "Sur une place en voirie gratuite au nord des voies", next: "Q3a_duree" },
			{ text: "Sur une place en zone bleue au sud des voies", next: "Q3a_duree" },
			{ text: "Sur une place en voirie gratuite au sud des voies", next: "Q3a_duree" },
			{ text: "Sur un stationnement privé (box ou place de parking privée)", next: "Q3a_duree" },
		],
	},
	{
		id: "Q3a_duree",
		text: "Combien de temps allez-vous laisser votre voiture stationnée ?",
		options: [
			{ text: "Moins de 2 heures", next: "Q4" },
			{ text: "Une demi-journée (entre 2 et 4 heures)", next: "Q4" },
			{ text: "Une journée entière (entre 4h et 12h)", next: "Q4" },
			{ text: "2 à 3 jours", next: "Q4" },
			{ text: "3 à 6 jours", next: "Q4" },
			{ text: "1 semaine ou plus", next: "Q4" },
		],
	},
	{
		id: "Q3b",
		text: "Où vous êtes-vous fait déposer ?",
		options: [
			{ text: "Sur la parking courte durée sur le parvis", next: "Q4" },
			{ text: "Sur le pont de Toulouse au niveau de la passerelle", next: "Q4" },
			{ text: "Autre", next: "Q3b_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q3b_precision",
		text: "Veuillez préciser l'endroit où vous vous êtes fait déposer :",
		freeText: true,
		next: "Q4",
	},
	{
		id: "Q3c",
		text: "Quelle ligne de bus/car avez-vous emprunté ?",
		options: [
			{ text: "Ligne B (réseau VIB)", next: "Q4" },
			{ text: "Ligne E (réseau VIB)", next: "Q4" },
			{ text: "Car Rémi", next: "Q4" },
			{ text: "Car TER", next: "Q4" },
			{ text: "Car scolaire", next: "Q4" },
			{ text: "Autre", next: "Q3c_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q3c_precision",
		text: "Précisez la ligne de bus/car empruntée :",
		freeText: true,
		next: "Q4",
	},
	{
		id: "Q3d",
		text: "Où avez-vous stationné votre vélo/trottinette ?",
		options: [
			{ text: "Sur les arceaux sur le parvis", next: "Q4" },
			{ text: "Dans l'abri vélo sécurisé Rémi sur le parvis", next: "Q4" },
			{ text: "Je le transporte avec moi dans le train", next: "Q4" },
			{ text: "Autre", next: "Q3d_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q3d_precision",
		text: "Veuillez préciser où vous avez stationné votre vélo/trottinette :",
		freeText: true,
		next: "Q4",
	},
	{
		id: "Q4",
		text: "Avez-vous emprunté la passerelle depuis le pont de Toulouse pour venir en gare ?",
		options: [
			{ text: "Oui", next: "Q5" },
			{ text: "Non", next: "Q5" },
		],
	},
	{
		id: "Q5",
		text: "Possédez-vous un abonnement TER ?",
		options: [
			{ text: "Oui", next: "Q6" },
			{ text: "Non", next: "Q6" },
		],
	},
	{
		id: "Q6",
		text: "Quelle sera votre gare de destination finale ?",
		options: [
			{ text: "Paris (Austerlitz ou Montparnasse)", next: "Q7" },
			{ text: "Bourges", next: "Q7" },
			{ text: "Orléans", next: "Q7" },
			{ text: "Tours", next: "Q7" },
			{ text: "Châteauroux", next: "Q7" },
			{ text: "Limoges", next: "Q7" },
			{ text: "Autre", next: "Q6_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q6_precision",
		text: "Précisez votre gare de destination finale :",
		usesGareSelector: true, 
		next: "Q7",
	},
	{
		id: "Q7",
		text: "Quel est le motif de votre déplacement en train ?",
		options: [
			{ text: "Je me rends sur mon lieu de travail", next: "Q8" },
			{ text: "Je me rends sur mon lieu d'études", next: "Q8" },
			{ text: "Je rentre à mon domicile principal", next: "Q7a" },
			{ text: "Déplacement professionnel", next: "Q8" },
			{ text: "Loisirs, tourisme", next: "Q8" },
			{ text: "Autres (Achats, démarches administratives, RDV médical...)", next: "Q7_precision", requiresPrecision: true },
		],
	},
	{
		id: "Q7_precision",
		text: "Précisez le motif de votre déplacement :",
		freeText: true,
		next: "Q8",
	},
	{
		id: "Q7a",
		text: "Quel était la raison de votre venue à Vierzon ?",
		options: [
			{ text: "Travail", next: "Q8" },
			{ text: "Etudes", next: "Q8" },
			{ text: "Déplacement professionnel", next: "Q8" },
			{ text: "Loisirs, tourisme", next: "Q8" },
			{ text: "Autres (Achats, démarches administratives, RDV médical, visite...)", next: "Q8" },
		],
	},
	{
		id: "Q8",
		text: "A quelle fréquence réalisez-vous ce déplacement en train ?",
		options: [
			{ text: "Tous les jours de la semaine ou presque (au moins 3 fois par semaine)", next: "Q9" },
			{ text: "Régulièrement (au moins une fois par mois)", next: "Q9" },
			{ text: "Occasionnellement (moins d'une fois par mois)", next: "Q9" },
		],
	},
	{
		id: "Q9",
		text: "Selon vous, que faudrait-il faire en priorité pour améliorer les conditions d'accès à cette gare ?",
		freeText: true,
		freeTextPlaceholder: "Votre réponse",
		next: "end",
	},

	// Section pour les non-voyageurs (accompagnateurs et autres)
	{
		id: "Q2_nv",
		text: "Quelle est l'origine de votre déplacement ? (D'où êtes-vous parti pour arriver à la gare ?)",
		options: [
			{ text: "Vierzon", next: "Q2a_nv" },
			{ text: "Autre commune", next: "Q2_precision_nv", requiresPrecision: true },
		],
	},
	{
		id: "Q2_precision_nv",
		text: "Préciser le nom de la commune :",
		freeText: true,
		next: "Q3_nv",
	},
	{
		id: "Q2a_nv",
		text: "De quelle rue de Vierzon venez-vous ?",
		streetInput: true,
		freeTextPlaceholder: "Nom de la rue",
		next: "Q3_nv",
	},
	{
		id: "Q3_nv",
		text: "Quel mode de transport avez-vous utilisé pour vous rendre à la gare ?",
		options: [
			{ text: "A pied", next: "Q4_nv" },
			{ text: "En voiture -- en tant que conducteur", next: "Q3a_nv" },
			{ text: "En voiture -- en tant que passager", next: "Q4_nv" },
			{ text: "En covoiturage avec un autre usager du train", next: "Q4_nv" },
			{ text: "En bus/car", next: "Q4_nv" },
			{ text: "A vélo", next: "Q4_nv" },
			{ text: "En trottinette", next: "Q4_nv" },
			{ text: "En Taxi/VTC", next: "Q4_nv" },
			{ text: "En 2 roues Motorisé (Moto, scooter...)", next: "Q3a_nv" },
			{ text: "Autre", next: "Q3_autre_nv", requiresPrecision: true },
		],
	},
	{
		id: "Q3_autre_nv",
		text: "Précisez le mode de transport utilisé :",
		freeText: true,
		next: "Q4_nv",
	},
	{
		id: "Q3a_nv",
		text: "Où avez-vous stationné votre véhicule ?",
		options: [
			{ text: "Sur le parking Effia longue durée", next: "Q4_nv" },
			{ text: "Sur le parking courte durée sur le parvis", next: "Q4_nv" },
			{ text: "Sur une place en voirie gratuite au nord des voies", next: "Q4_nv" },
			{ text: "Sur une place en zone bleue au sud des voies", next: "Q4_nv" },
			{ text: "Sur une place en voirie gratuite au sud des voies", next: "Q4_nv" },
			{ text: "Sur un stationnement privé (box ou place de parking privée)", next: "Q4_nv" },
		],
	},
	{
		id: "Q4_nv",
		text: "Avez-vous emprunté la passerelle depuis le pont de Toulouse pour venir en gare ?",
		options: [
			{ text: "Oui", next: "Q5_nv" },
			{ text: "Non", next: "Q5_nv" },
		],
	},
	{
		id: "Q5_nv",
		text: "Selon vous, que faudrait-il faire en priorité pour améliorer les conditions d'accès à cette gare ?",
		freeText: true,
		freeTextPlaceholder: "Votre réponse",
		next: "end",
	},
];